// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaA2HS4JJL8-OZ73AUcaifTuRJZZPbMeQ',
    appId: '1:714952542642:web:5c001c9a8c369c3d397cab',
    messagingSenderId: '714952542642',
    projectId: 'petcare-myapp',
    authDomain: 'petcare-myapp.firebaseapp.com',
    storageBucket: 'petcare-myapp.firebasestorage.app',
    measurementId: 'G-J0JLBZMD8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaA2HS4JJL8-OZ73AUcaifTuRJZZPbMeQ',
    appId: '1:714952542642:android:ea899543aa7c962b397cab',
    messagingSenderId: '714952542642',
    projectId: 'petcare-myapp',
    storageBucket: 'petcare-myapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaA2HS4JJL8-OZ73AUcaifTuRJZZPbMeQ',
    appId: '1:714952542642:android:ea899543aa7c962b397cab',
    messagingSenderId: '714952542642',
    projectId: 'petcare-myapp',
    storageBucket: 'petcare-myapp.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaA2HS4JJL8-OZ73AUcaifTuRJZZPbMeQ',
    appId: '1:714952542642:android:ea899543aa7c962b397cab',
    messagingSenderId: '714952542642',
    projectId: 'petcare-myapp',
    storageBucket: 'petcare-myapp.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaA2HS4JJL8-OZ73AUcaifTuRJZZPbMeQ',
    appId: '1:714952542642:web:5c001c9a8c369c3d397cab',
    messagingSenderId: '714952542642',
    projectId: 'petcare-myapp',
    authDomain: 'petcare-myapp.firebaseapp.com',
    storageBucket: 'petcare-myapp.firebasestorage.app',
    measurementId: 'G-J0JLBZMD8V',
  );
}